# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: extractions_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='extractions_data.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x65xtractions_data.proto\"a\n\nExtraction\x12\x0b\n\x03rpm\x18\x01 \x03(\x02\x12\x0e\n\x06torque\x18\x02 \x03(\x02\x12\x11\n\ttimestamp\x18\x03 \x03(\x01\x12\x10\n\x08latitude\x18\x04 \x01(\x01\x12\x11\n\tlongitude\x18\x05 \x01(\x01\"2\n\x0e\x45xtractionList\x12 \n\x0b\x65xtractions\x18\x01 \x03(\x0b\x32\x0b.Extractionb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EXTRACTION = _descriptor.Descriptor(
  name='Extraction',
  full_name='Extraction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rpm', full_name='Extraction.rpm', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='torque', full_name='Extraction.torque', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Extraction.timestamp', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Extraction.latitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Extraction.longitude', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=123,
)


_EXTRACTIONLIST = _descriptor.Descriptor(
  name='ExtractionList',
  full_name='ExtractionList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='extractions', full_name='ExtractionList.extractions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=175,
)

_EXTRACTIONLIST.fields_by_name['extractions'].message_type = _EXTRACTION
DESCRIPTOR.message_types_by_name['Extraction'] = _EXTRACTION
DESCRIPTOR.message_types_by_name['ExtractionList'] = _EXTRACTIONLIST

Extraction = _reflection.GeneratedProtocolMessageType('Extraction', (_message.Message,), dict(
  DESCRIPTOR = _EXTRACTION,
  __module__ = 'extractions_data_pb2'
  # @@protoc_insertion_point(class_scope:Extraction)
  ))
_sym_db.RegisterMessage(Extraction)

ExtractionList = _reflection.GeneratedProtocolMessageType('ExtractionList', (_message.Message,), dict(
  DESCRIPTOR = _EXTRACTIONLIST,
  __module__ = 'extractions_data_pb2'
  # @@protoc_insertion_point(class_scope:ExtractionList)
  ))
_sym_db.RegisterMessage(ExtractionList)


# @@protoc_insertion_point(module_scope)
