# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vesc_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vesc_data.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0fvesc_data.proto\"a\n\nextraction\x12\x0b\n\x03rpm\x18\x01 \x03(\x02\x12\x0e\n\x06torque\x18\x02 \x03(\x02\x12\x11\n\ttimestamp\x18\x03 \x03(\x01\x12\x10\n\x08latitude\x18\x04 \x01(\x01\x12\x11\n\tlongitude\x18\x05 \x01(\x01\"/\n\x08VescData\x12#\n\x0e\x65xtractionList\x18\x01 \x03(\x0b\x32\x0b.extractionb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EXTRACTION = _descriptor.Descriptor(
  name='extraction',
  full_name='extraction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rpm', full_name='extraction.rpm', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='torque', full_name='extraction.torque', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='extraction.timestamp', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='extraction.latitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='extraction.longitude', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=116,
)


_VESCDATA = _descriptor.Descriptor(
  name='VescData',
  full_name='VescData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='extractionList', full_name='VescData.extractionList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=165,
)

_VESCDATA.fields_by_name['extractionList'].message_type = _EXTRACTION
DESCRIPTOR.message_types_by_name['extraction'] = _EXTRACTION
DESCRIPTOR.message_types_by_name['VescData'] = _VESCDATA

extraction = _reflection.GeneratedProtocolMessageType('extraction', (_message.Message,), dict(
  DESCRIPTOR = _EXTRACTION,
  __module__ = 'vesc_data_pb2'
  # @@protoc_insertion_point(class_scope:extraction)
  ))
_sym_db.RegisterMessage(extraction)

VescData = _reflection.GeneratedProtocolMessageType('VescData', (_message.Message,), dict(
  DESCRIPTOR = _VESCDATA,
  __module__ = 'vesc_data_pb2'
  # @@protoc_insertion_point(class_scope:VescData)
  ))
_sym_db.RegisterMessage(VescData)


# @@protoc_insertion_point(module_scope)
